name: Azure deployment from bicep

on: 
  workflow_dispatch:
    inputs:
      repository_name:
        description: repository name
        required: true
        default: golang-appservice-test-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: create git repo
      run: |
        echo 'clone_url='$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          ${{ secrets.GH_ORG }} \
          -d '{"name":"${{ github.event.inputs.repository_name }}","description":"This is your first repository","homepage":"https://github.com","private":false,"has_issues":true,"has_projects":true,"has_wiki":true}' \
          | jq .clone_url) >> $GITHUB_ENV

    - name: echo
      run: echo ${{ env.clone_url }}

    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    #- name: deploy
    #  uses: azure/arm-deploy@v1
    #  with:
    #    subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #    resourceGroupName: ${{ secrets.AZURE_RG }}
    #    template: ./main.bicep
    #    parameters: 'parameter.json'
    #   failOnStdErr: false

  functions:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: call azure functions
        run: echo call functions