name: Azure deployment from bicep

on: 
  push:
    branches:
      - main

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
    - name: create git repository
      run: echo create repo

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: 'parameter.json'
        failOnStdErr: false

  functions:
    runs-on: ubuntu-latest
    steps:
      - name: call azure functions
        run: echo call functions