name: echo action

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo hello
  bye:
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo bye